### ISSUE TITLE
NALU type checking

### ISSUE THREAD

**Issue by adrian-niculescu** [schiermike/h264-sei-parser#1]
In your check
`if (payload_type != 45)`
you assume that NRI=10 (in binary) but strictly speaking you only need to check the NALU type which is the first 5 bits, like this: `if ((payload_type & 0x1F) == 6)`

Realistically, I know your code should work without problems, but it's something you might want to be aware of.

**Comment by schiermike** [comment]
Hey Adrian,
thanks for your comment. To be honest, it's been a while since I've last done work in this domain, so took a while to wrap my head around this.

`payload_type` is not the NAL unit type, it's the payload type of the supplemental enhancement information. The NAL unit type gets checked at line 121 - I believe it's safe to assume that the first three bits are zero (that is, the forbidden_zero_bit and the nal_ref_idc) as this is what the standard states. 

I check for `payload_type != 45` since 45 is the frame-packing-arrangement SEI payload type.

I should've really documented this better, but this was just a quick hack ...
